### ISSUE TITLE
Govpress in IE under compatibility view.

### ISSUE THREAD

**Issue by FrankHablawi** [govfresh/govpress#100]
Hello!

If you look at any site running Govpress in IE under Compatibility View, it breaks. Homepage title is visible, menus disappear, and widget areas break.

This is even true of http://govpress.co

Since this theme is designed for government use, I would suggest this issue be addressed - typically compatibility with a broad amount of older browsers is vital.

Thanks!

**Comment by devinsays** [comment]
I've done some reading on this. If we explicitly set a compatible version, it should disable the compatibility view:

```
<meta http-equiv="X-UA-Compatible" content="IE=10">
```

I'm going to commit this, but will require some browser testing before I can close this ticket out.
