### ISSUE TITLE
Heading links and links with bold letters turn into strikethrough

### ISSUE THREAD

**Issue by errrkey** [govfresh/govpress#101]
Heading links and links that are in bold letters appear as strikethrough (words with lines like crash-outs for broken links). It confuses people that links are broken even though they're not.

**Comment by devinsays** [comment]
Hi @errrkey, I haven't been able to reproduce this issue. Can you post a screenshot for me with the example html you're using for the title?

Is it possible you have an unclosed strikethrough tag earlier on your page somewhere?

Please re-open this issue if this is still a problem and you have steps to reproduce. Thanks!
