### ISSUE TITLE
Hiding Page Titles

### ISSUE THREAD

**Issue by pmonet14** [govfresh/govpress#106]
Is there a way to hide the page titles? I have not found where I can disable this within the Govpress theme.

newportvermont.org

**Comment by lukefretwell** [comment]
@pmonet14 can you send a screenshot of which title you're talking about?

**Comment by pmonet14** [comment]
Hello,

Attached is a screen capture showing what I am talking about.

Thanks.

Paul Monette

On Mon, Feb 1, 2016 at 1:12 PM, Luke Fretwell <notifications@github.com>
wrote:

> @pmonet14 <https://github.com/pmonet14> can you send a screenshot of
> which title you're talking about?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/govfresh/govpress/issues/106#issuecomment-178105717>.
>



-- 
Paul L. Monette, Mayor
City of Newport
222 Main Street
Newport, VT 05855

Tel: 802.334.1021
Cel: 802.673.9002
Email: Paul.Monette@newportvermont.org

Privacy and Confidentiality Notice: This message is for the designated
recipient only and may contain privileged, confidential or otherwise private
information. If you have received it in error, please notify the sender
immediately and delete the original. Any unauthorized review, forwarding,
copying, use, disclosure or distribution without the prior consent of the
sender is strictly prohibited.

**Comment by lukefretwell** [comment]
@pmonet14 I don't see it here?
