### ISSUE TITLE
pr-BR translation, need help to put into production?

### ISSUE THREAD

**Issue by ppKrauss** [govfresh/govpress#108]
There are no pt-BR translation at [govpress/languages](https://github.com/govfresh/govpress/tree/master/languages), but it is at https://github.com/govfresh/govpress/pull/98 (since  May 2015).

**Comment by devinsays** [comment]
Much delayed response, but translations should now be submitted through wordpress.org: https://translate.wordpress.org/projects/wp-themes/govpress/

We'll be releasing a new version of this theme shortly.
