### ISSUE TITLE
Can we display incon menu on posts?

### ISSUE THREAD

**Issue by shakirahmed100** [govfresh/govpress#71]
Can we display incon menu on posts? We know normally incon menu shows on pages (when we select home template). But there is no option to select home template while posting articles as post. So, is there any way we can display incon menu on posts?

Thanks

**Comment by devinsays** [comment]
You can put the icon menu on any template, but it would require you to edit that template. If you want the menu on single.php, you could add this code:

```
<?php if ( has_nav_menu( 'icon' ) ) : ?>
	<div id="menu-icon" class="clear">
		<div class="col-width">
			<?php
			wp_nav_menu( array(
				'theme_location' => 'icon',
				'depth' => '1',
				'container_class' => 'menu-icon-container'
			) ); ?>
		</div>
	</div>
<?php endif; // Icon Menu ?>
```

Right after the header call.
