### ISSUE TITLE
Homepage featured blog posts with thumbnails

### ISSUE THREAD

**Issue by lukefretwell** [govfresh/govpress#82]
Would be great to have a section on the homepage for featured blog posts similar to what UK.gov does:

![screen shot 2014-12-28 at 9 29 23 am](https://cloud.githubusercontent.com/assets/1569463/5564415/2431f6ac-8e74-11e4-8ada-6fb689755564.png)

And especially the new Philly alpha:

![screen shot 2014-12-28 at 9 30 23 am](https://cloud.githubusercontent.com/assets/1569463/5564416/3be1a2d4-8e74-11e4-8bd3-a42698eb9074.png)

Perhaps, if enabled, displays below the link list section and above main page content.

I think the above could work with a plugin in the home page featured section, but can't seem to find an elegant solution.

**Comment by rajeshmepco** [comment]
I am also expecting thumbnail image on posts. Can you please guide.
