### ISSUE TITLE
Secondary page header with search?

### ISSUE THREAD

**Issue by lukefretwell** [govfresh/govpress#83]
What do you think about having search in the header on secondary pages with left-aligned logo?

See: 

* https://www.gov.uk/browse/disabilities
* http://alpha.phila.gov/browse/business/

**Comment by devinsays** [comment]
I think search is an important element for sites like this, but I don't want to break anything for existing users. Let's add it as an option to the menu, along with social buttons.

Opened new issue: https://github.com/govfresh/govpress/issues/105
