### ISSUE TITLE
Icons not showing on my page

### ISSUE THREAD

**Issue by twohearts0001** [govfresh/govpress#86]
Hi Team,

I am not able to see Icons in the home page, please suggest me ........

And also suggest me how to change the menu's background color.

Regards,
Santosh

**Comment by devinsays** [comment]
You can change the menu's background color by adjusting "Primary Color" in the color options under "Theme > Customize".

For the icons on the home page, have you followed all the instructions?
http://govpress.co/help/homepage-setup/

If it's set up correctly, and still not woking, can you post a link for us to look at?
