### ISSUE TITLE
Changes not going live

### ISSUE THREAD

**Issue by jjjbluray** [govfresh/govpress#87]
I have looked briefly over the list of issues and did not see this one. I have installed the govpress theme and used plugin to create a child theme due to reading a couple posts saying child themes help keep problems at bay when updates to the original theme happen. I made many changes to the Customize panel and in the admin panel I can see them all when I view the website from there. However, when I log out and go to the site as a normal person the only thing showing is the default theme colors and no background pic. 
I am also noticing that the Icon menu in the middle drops one of the icons into a second row in the middle of the menu everytime I view the site. I have to refresh the page to get it back in the same line with the others. Thanks for any ideas!

**Comment by devinsays** [comment]
Hi @jjjbluray.

What is the URL for your site?

Are you clicking "Save" after you make your customizations? Can you view the changes on the site while logged in, or only when you're in the "customize" panel?

**Comment by jjjbluray** [comment]
Do websites have brain farts because I left it alone for an hour or so this morning and when I went back it is cooperating. Early this morning I could only see the changes while logged in. If I logged out they were default. Logged back in and the changes were in the admin panel again. Hope I didn't completely waste your time. Thank you for the fast response!

**Comment by devinsays** [comment]
No problem. Based on what you've said, there's a good chance it could be due to caching. If you are using a cache plugin on your site, make sure to clear it after making updates.

**Comment by lukefretwell** [comment]
+++ Thank you, @devinsays. @jjjbluray, would love to see the site!
