### ISSUE TITLE
Wrong rendering icon in GovPress Theme

### ISSUE THREAD

**Issue by antoniobosio** [govfresh/govpress#88]
Hi,
I have a problem with some icon in GovPress Theme 1.4.0 in Wordpress 4.1.
I don't see two icon (the search lens and the sub menu triangle).
You can see the screenshot in attachment.

Can you help me ?
![govpress_errore2](https://cloud.githubusercontent.com/assets/6931815/5972626/162cbfee-a85d-11e4-8cac-bb0e176143a9.jpg)
![govpress_errore](https://cloud.githubusercontent.com/assets/6931815/5972625/161ee5e0-a85d-11e4-82f3-89e058735697.jpg)

Thanks
Antonio

**Comment by devinsays** [comment]
Is this a live site? Can you give me a URL to check?

**Comment by antoniobosio** [comment]
Yes. The link is this:
http://www.parrocchiavillafrancapiemonte.it

Thanks
Antonio
 Il 30/gen/2015 19:24 "Devin Price" <notifications@github.com> ha scritto:

**Comment by devinsays** [comment]
The stylesheet for "fontawesome-css" is not enqueuing for some reason. Have you made any customizations to the theme?

Could you try disabling all your plugins for a minute and check to see if one of them might be conflicting?

**Comment by antoniobosio** [comment]
Yes, i have installed the plugin "simple custom CSS" in order to modify
some part of event google calendar widget.
Now i have disabled all plugin.
Antonio
Il 30/gen/2015 19:45 "Devin Price" <notifications@github.com> ha scritto:

**Comment by devinsays** [comment]
Well, disabling all your plugins seemed to fix it. I'd re-enable one by one until you find which plugin is causing the conflict.

Re-open this ticket if you have another question.

**Comment by lukefretwell** [comment]
@antoniobosio you might also try the CSS tool that comes with JetPack as another option.

**Comment by antoniobosio** [comment]
The problem is nextgen gallery optimizer.
Thanks for the support.

Best regards
Antonio
Il 30/gen/2015 20:08 "Devin Price" <notifications@github.com> ha scritto:
