### ISSUE TITLE
Featured Image not coming on posts

### ISSUE THREAD

**Issue by rajeshmepco** [govfresh/govpress#95]
When we create posts with featured image it is not coming by default but for other themes it works fine. Is there any specific change we need to be done?

Appreciate your advice.

**Comment by devinsays** [comment]
Hi @rajeshmepco. This theme does not automatically output the featured image.

**Comment by rajeshmepco** [comment]
Hi @devinsays 
Thanks. But  we need it in our case. How can We enable it to populate automatically?

**Comment by devinsays** [comment]
You can create a child theme and add something like this to single.php:

```
<?php if ( has_post_thumbnail() ) { ?>
<figure class="entry-image">
	<?php the_post_thumbnail(); ?>
</figure>
<?php } ?>
```
