### ISSUE TITLE
The theme is not working in ie11

### ISSUE THREAD

**Issue by countywebteam** [govfresh/govpress#99]
I have been testing the theme in chrome, and it has worked fine. However, I just went to the site in internet explorer 11 and it doesnt work. Is there a reason it looks so different. When I went to http://www.cityofferndale.org/ in ie it worked fine. Is there something in the settings, or code that I have to insert? Hopefully you can fix this issue because you have created a very functional theme. I look forward to hearing from you

I have attached some photos
Chrome:
![chrome wordpress](https://cloud.githubusercontent.com/assets/12833476/8088898/9b4f10e2-0f72-11e5-939e-510ecba9d657.JPG)

Internet explorer 11:
![wordpress ie](https://cloud.githubusercontent.com/assets/12833476/8088910/a9cb6558-0f72-11e5-923b-6cfb71125777.JPG)

**Comment by devinsays** [comment]
Try disabling all your plugins just to check if there is a conflict somewhere. It looks like the icon font isn't loading, so I might start with any plugins that may add their own fonts.

If you can send a link to a live or test site, I'd be happy to take a look.

**Comment by countywebteam** [comment]
Thank you for your response. I disabled all of my plugins and it still didn't render correctly. I would send you a link to the site, however it is on a test server on our internal network. We are not allowed to have someone from the outside have access to it. Would it help if I sent you an html file of a couple of pages?
![dept wordpress](https://cloud.githubusercontent.com/assets/12833476/8108775/85d75cd4-1020-11e5-8983-305aa841c5a3.JPG)

**Comment by devinsays** [comment]
That wouldn't really be helpful, I'd need to have access to all the resources to debug.

Does our demo site load fine for you in IE11? http://www.govpress.co/

**Comment by countywebteam** [comment]
From what I can see it loads correctly.
I will send you the whole WordPress file. What is you email address?

**Comment by devinsays** [comment]
The only way for me to debug is to have a publicly accessible site where the issue is produced.

If you have a web developer in your department, perhaps you could have them take a look. Or, try debugging on your own using the IE11 developer tools to see if you can find where the error is being produced: http://blogs.msdn.com/b/ie/archive/2013/07/29/debugging-and-tuning-web-sites-and-apps-with-f12-developer-tools-in-ie11.aspx

**Comment by countywebteam** [comment]
Ok. We will replicate the same site on an outside server and see if we have the same issue (there might be an issue with our internal one). However, this process will take a few days (most likely by next week). How long would it take you to debug? A day or a few days? Can you give me your email and I will send you the information when the site is complete. Thanks again for all of the help

**Comment by devinsays** [comment]
Just ping this ticket. I get e-mail alerts.

**Comment by FrankHablawi** [comment]
I believe this might be related to my issue here:
https://github.com/govfresh/govpress/issues/100

@countywebteam is your site being viewed under compatibility view settings?

**Comment by devinsays** [comment]
Closing this issue due to lack of response. Compatibility view could indeed cause an issue like this.
